#!/usr/bin/env bash
# this script installs a nginx web server on web-01 server

# update the package index
sudo apt-get update

# install nginx with -y option to avoid prompts
sudo apt-get install -y nginx

# Create a file named hello_world in /var/www/html directory
echo "Hello World!" | sudo tee /var/www/html/hello_world

# modify the default configuration file of nginx to serve the hellow_world
sudo sed -i 's/index.nginx-debian.html/hello_world/' /etc/nginx/sites-enabled/default

# Restart nginx using service command
sudo service nginx restart
