#!/usr/bin/env bash
# This script installs nginx web server on web-01 server

# Update the package index
sudo apt-get -y update

# Install nginx with -y option to avoid prompts
sudo apt-get -y install nginx

# Start nginx using service command
sudo service nginx start

# Create a file named index.nginx-debian.html
# in /var/www/html directory with the content "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Modify the default configuration file of nginx
# to remove the default_server option from the listen directive
sed -i "s/listen 80 default_server;/listen 80;/g" /etc/nginx/sites-available/default
