#!/usr/bin/env bash
# This script configures a new Ubuntu machine to redirect /redirect_me

# Update the package index
sudo apt-get update

# Install nginx with -y option to avoid prompts
sudo apt-get install -y nginx

# Create a file named redirect_me in /var/www/html directory
echo "Redirecting..." | sudo tee /var/www/html/redirect_me

# Modify the default configuration file of Nginx to add a rewrite rule for /redirect_me
sudo sed -i '/listen 80 default_server;/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default

# Reload Nginx service to apply the changes
sudo service nginx restart
