#!/usr/bin/env bash
# This script creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

handle_signal() {
	signal="$1"
	case "$signal" in
		2)
			echo "Y U no love me?!"
			;;
		3|15)
			echo "I hate the kill command"
			rm /var/run/myscript.pid
			exit 0
			;;
		*)
			;;
	esac
}

trap 'handle_signal 2' SIGINT
trap 'handle_signal 3' SIGQUIT
trap 'handle_signal 15' SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
