#!/bin/env bash
# This script print numbers from 1 to 20 but display bad luck from China with 4th
# diplays bad luck from Japan with 9th, bad luck from Italy with 17th

i=1
while (( i <= 20))
do
	if (( i == 4 ))
	then
		echo "bad luck from China"
	elif (( i == 9 ))
	then
		echo "bad luck from Japan"
	elif (( i == 17 ))
	then
		echo "bad luck from Italy"
	else
		echo "$i"
	fi
	(( i++))
done
