#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

sed -i 's/user .*/user nginx nginx;/' /etc/nginx/nginx.conf || exit 1
sed -i 's/listen .*/listen 8080;/' /etc/nginx/sites-available/default || exit 2
systemctl reload nginx & echo
